version: '3'

services:
  php:
    container_name: "test_task_php"
    build: docker/php
    tty: true
    volumes:
      - ./docker/php/z-overrides.ini:/usr/local/etc/php/conf.d/z-overrides.ini
      - ./:/app
    working_dir: /app
  nginx:
    container_name: "test_task_nginx"
    build: docker/nginx
    tty: true
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports:
      - "6002:80"
    depends_on:
      - php
    links:
      - php
  redis:
    container_name: "test_task_redis"
    image: bitnami/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      REDIS_PASSWORD: "9dE5WAxZz2k5"
      REDIS_PORT_NUMBER: "6379"
