version: '3'

services:
  php:
    container_name: "test_task_php_inline"
    build: docker/php_inline
    tty: true
    volumes:
      - ./docker/php/z-overrides.ini:/usr/local/etc/php/conf.d/z-overrides.ini
      - ./:/app
    working_dir: /app
  redis:
    container_name: "test_task_redis_inline"
    image: bitnami/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      REDIS_PASSWORD: "9dE5WAxZz2k5"
      REDIS_PORT_NUMBER: "6379"
    depends_on:
      - php
